### ISSUE TITLE
String formatting error making project un-runnable on Android Studio 3.1.4

### ISSUE THREAD

**Issue by codingjeremy** [android/graphics-samples#1]
<a href="https://github.com/ghost"><img src="https://avatars3.githubusercontent.com/u/10137?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ghost](https://github.com/ghost)**
_Thursday Sep 13, 2018 at 05:43 GMT_
_Originally opened as https://github.com/googlesamples/android-DrawableTinting/issues/1_

----

I'm having issues getting this going.  It's probably some issue with my Android Studio configuration, but I'm not experienced enough to know.  I have a stackoverflow question on it that explains further:

https://stackoverflow.com/questions/52307125/why-doesnt-this-drawable-tinting-android-code-sample-work-out-of-the-box

I tried commenting out the offending lines... which I assumed simply setText in a textview... and now the app runs... but it doesn't seem to do what it claims... as the textview is a different color than the button... and neither one changes color or appearance as a result of being focused/clicked, etc.

**Comment by yaraki** [comment]
I verified that the app builds and runs fine on Studio 3.6.1.
Please open a new issue if the problem persists.
