### ISSUE TITLE
Does not show annotations

### ISSUE THREAD

**Issue by codingjeremy** [android/graphics-samples#20]
<a href="https://github.com/RaulVelasco84"><img src="https://avatars1.githubusercontent.com/u/28058752?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [RaulVelasco84](https://github.com/RaulVelasco84)**
_Friday Mar 02, 2018 at 13:16 GMT_
_Originally opened as https://github.com/googlesamples/android-PdfRendererBasic/issues/22_

----

The library is fine but I can not show the annotations that have a pdf file

**Comment by yaraki** [comment]
PdfRenderer API does not support PDF annotations.
