### ISSUE TITLE
How to use in android 17 (api)

### ISSUE THREAD

**Issue by codingjeremy** [android/graphics-samples#21]
<a href="https://github.com/ghasem110deh"><img src="https://avatars1.githubusercontent.com/u/12730418?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ghasem110deh](https://github.com/ghasem110deh)**
_Tuesday Apr 17, 2018 at 02:07 GMT_
_Originally opened as https://github.com/googlesamples/android-PdfRendererBasic/issues/23_

----

hi
i use this lib in android 21 (lollipop) an work, how to use in android 17 (api) ?
thank's

**Comment by yaraki** [comment]
PdfRenderer is available only on API level 21 and above.
