### ISSUE TITLE
Play Protect blocks "DisplayingBitmaps" sample...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/graphics-samples#29]
This should really get updated...

![image](https://user-images.githubusercontent.com/5357526/65394879-9c180500-dd9b-11e9-94b1-73649f332dc9.png)

**Comment by yaraki** [comment]
Fixed in #33.

**Comment by AndroidDeveloperLB** [comment]
Confirmed. Say, what is the red frame near the edges that appear almost each time I press a thumbnail?

It doesn't always appear...
About 4 out of 5 times...


[device-2019-10-20-113941.zip](https://github.com/android/graphics-samples/files/3747647/device-2019-10-20-113941.zip)
