### ISSUE TITLE
Android Studio can't build project

### ISSUE THREAD

**Issue by coditive** [android/graphics-samples#37]
Android Studio is complaining about gradle-properties, as it should contain android.useAndroidX=true field. I think it's silly issue, but this repo does not have gradle.properties of it's own. Please ignore if i am wrong or guide me.

**Comment by yaraki** [comment]
Hi, which project are you trying to import?

**Comment by coditive** [comment]
@yaraki Hi, I was trying to build pdfRendererBasicKotlin and i got that error from android studio.
